<?xml version="1.0" encoding="UTF-8"?>
<project name="jurisPro" default="default" basedir=".">
    <description>Builds, tests, and runs the project jurisPro.</description>
    <import file="nbproject/build-impl.xml"/>

    <!-- Copia las vistas y estilos a la carpeta de salida -->
    <target name="-post-compile">
        <copy todir="${build.classes.dir}">
            <fileset dir="${src.dir}">
                <include name="**/*.fxml"/>
                <include name="**/*.css"/>
            </fileset>
        </copy>
    </target>

</project>